name: http_server_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/developerabhi2507/http_server_project.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  http_parser: ^4.1.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
